name: BSF Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, edited]

permissions: write-all

jobs:
  CHECK_SHORTCODE:
    if: ${{ github.event.action == 'edited' || contains(github.event.pull_request.body, '[BSF-PR-SUMMARY]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: WRITE PR SUMMARY
        uses: brainstormforce/pull-request-reviewer@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ACTION_CONTEXT: 'CHECK_SHORTCODE'
          EXCLUDE_EXTENSIONS: "md, yml, lock"
          INCLUDE_EXTENSIONS: "php, js, jsx, ts, tsx, css, scss, html, json"
          EXCLUDE_PATHS: "node_modules/,vendor/"

  CODE_REVIEW:
    needs: CHECK_SHORTCODE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: AI CODE REVIEW
        uses: brainstormforce/pull-request-reviewer@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ACTION_CONTEXT: "CODE_REVIEW"
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          EXCLUDE_EXTENSIONS: "md, yml, lock"
          INCLUDE_EXTENSIONS: "php, js, jsx, ts, tsx, css, scss, html, json"
          EXCLUDE_PATHS: "node_modules/,vendor/"